export const VENDORS = {
  DELL: "Dell India",
  HP: "HP India",
  LENOVO: "Lenovo India",
  APPLE: "Apple India",
  ASUS: "ASUS India",
  ACER: "Acer India",
  MSI: "MSI India",
  SAMSUNG: "Samsung India",
  LG: "LG Electronics India",
  CANON: "Canon India",
  EPSON: "Epson",
  BROTHER: "Brother",
  LOGITECH: "Logitech India",
  RAZER: "Razer",
  CORSAIR: "Corsair",
  CISCO: "Cisco Systems India",
  UBIQUITI: "Ubiquiti",
  NETGEAR: "Netgear",
  TPLINK: "TP-Link India",
  ZEBRONICS: "Zebronics India",
  MICROSOFT: "Microsoft",
  ADOBE: "Adobe",
  SYMANTEC: "Symantec",
  INTEL: "Intel",
  AMD: "AMD",
  NVIDIA: "NVIDIA",
  CRUCIAL: "Crucial",
  KINGSTON: "Kingston",
  WESTERN_DIGITAL: "Western Digital",
  SEAGATE: "Seagate",
  SONY: "Sony",
  JABRA: "Jabra",
  POLY: "Poly",
  HERMAN_MILLER: "Herman Miller",
  STEELCASE: "Steelcase",
  GODREJ_INTERIO: "Godrej Interio",
  APC: "APC",
  CYBERPOWER: "CyberPower",
  WACOM: "Wacom",
  BENQ: "BenQ",
  EATON: "Eaton",
  KEYCHRON: "Keychron",
  HYPERX: "HyperX",
  BOSE: "Bose",
  JBL: "JBL",
  SYNOLOGY: "Synology",
  QNAP: "QNAP",
  ALL: "All"
};
